# Generated by Django 5.2.7 on 2025-11-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='filemanager',
            new_name='core_file_m_parent__4ea7da_idx',
            old_name='system_file_parent__ba2823_idx',
        ),
        migrations.RenameIndex(
            model_name='filemanager',
            new_name='core_file_m_storage_e9e0e5_idx',
            old_name='system_file_storage_ea4a34_idx',
        ),
        migrations.AlterModelTable(
            name='filemanager',
            table='core_file_manager',
        ),
    ]
